export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const GET_CURRENT_SERVICES = "GET_CURRENT_SERVICES";
export const GET_ALL_SERVICE_TYPES = "GET_ALL_SERVICE_TYPES";
export const SET_CURRENT_SERVICE_TYPE = "SET_CURRENT_SERVICE_TYPE";
export const SET_LOADING = "SET_LOADING";
export const SET_PROGRESS = "SET_PROGRESS";
export const SEARCH_SERVICES = "SEARCH_SERVICES";
